# Generated by Django 3.1.4 on 2020-12-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
    ]
